[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node backend-server.js"

[variables]
NODE_ENV = "production"
