[phases.setup]
nixPkgs = ["nodejs_18"]
aptPkgs = []

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node backend-server.js"

[variables]
NPM_CONFIG_PRODUCTION = "false"
